
CREATE TABLE contatos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL,
    fone VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    data_criacao DATETIME NOT NULL,
    apelido VARCHAR(30),
    PRIMARY KEY (id)
);