
CREATE TABLE contatos (
    idcon BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL,
    fone VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    apelido VARCHAR(30),
    PRIMARY KEY (idcon)
);